name = "promptmycircumstance"
compatibility_date = "2024-05-26"
main = "worker.js"

[build]
command = "bash build.sh"

[assets]
directory = "output/wwwroot"
not_found_handling = "single-page-application"

[ai]
binding = "AI"
